etproject/etproject/urls.py
from django.contrib import admin
from django.urls import path, include
from wagonauto import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.index,name='index'),
    path('admin/', admin.site.urls),
    path('wagonauto/',include(('wagonauto.urls','wagonauto'),namespace = 'wagonauto')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

etproject/wagonauto/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('companies/',views.CompanyListView.as_view(),name='clist'),
    path('suzuki/',views.SuzukiListView.as_view(),name='suzukilist'),
    path('hyundai/',views.HyundaiListView.as_view(),name='hyundailist'),
    path('tata/',views.TataListView.as_view(),name='tatalist'),
    path('toyota/',views.ToyotaListView.as_view(),name='toyotalist'),
    path('mahindra/',views.MahindraListView.as_view(),name='mahindralist'),
    path('honda/',views.HondaListView.as_view(),name='hondalist'),
    path('kia/',views.KiaListView.as_view(),name='kialist'),
    path('suzuki/<int:pk>/',views.SuzukiDetailView.as_view(),name='suzukidetail'),
    path('hyundai/<int:pk>/',views.HyundaiDetailView.as_view(),name='hyundaidetail'),
    path('tata/<int:pk>/',views.TataDetailView.as_view(),name='tatadetail'),
    path('toyota/<int:pk>/',views.ToyotaDetailView.as_view(),name='toyotadetail'),
    path('mahindra/<int:pk>/',views.MahindraDetailView.as_view(),name='mahindradetail'),
    path('honda/<int:pk>/',views.HondaDetailView.as_view(),name='hondadetail'),
    path('kia/<int:pk>/',views.KiaDetailView.as_view(),name='kiadetail'),
    path('contacts/',views.ContactPage.as_view(),name='contlist'),
]

etproject/wagonauto/models.py
from django.db import models

# Create your models here.
class Companies(models.Model):
    company_name = models.CharField(max_length=20)
    logo = models.ImageField(upload_to='company_logos')

    def __str__(self):
        return self.company_name

class Suzuki(models.Model):
    car_name = models.CharField(max_length=20)
    car_pic = models.ImageField(upload_to='suzuki_cars')
    price = models.CharField(max_length=30)
    about = models.TextField(default = "About")
    engine_type = models.CharField(max_length=64,default="Type 0")
    max_power = models.CharField(max_length=64,default="0 @ 0rpm")
    max_torque = models.CharField(max_length=64,default="0 @ 0rpm")
    no_cylinders = models.PositiveIntegerField(default = 0)
    valves_per_cylinder = models.PositiveIntegerField(default = 0)
    transmission_type = models.CharField(max_length=64,default="Automatic")
    gear_box = models.CharField(max_length=64,default="5 gears")
    fuel_type = models.CharField(max_length=64,default="P/D/C")
    mileage = models.FloatField(default = 0)
    tank_capacity = models.FloatField(default = 0)
    emission_norm = models.CharField(max_length=64,default="BS IV")
    length = models.PositiveIntegerField(default = 0)
    width = models.PositiveIntegerField(default = 0)
    weight = models.PositiveIntegerField(default = 0)
    height = models.PositiveIntegerField(default = 0)
    boot_space = models.PositiveIntegerField(default = 0)
    seating = models.PositiveIntegerField(default = 0)
    others = models.TextField(default = "Others")

    def __str__(self):
        return self.car_name

class Hyundai(models.Model):
    car_name = models.CharField(max_length=20)
    car_pic = models.ImageField(upload_to='hyundai_cars')
    price = models.CharField(max_length=20)
    about = models.TextField(default = "About")
    engine_type = models.CharField(max_length=64,default="Type 0")
    max_power = models.CharField(max_length=64,default="0 @ 0rpm")
    max_torque = models.CharField(max_length=64,default="0 @ 0rpm")
    no_cylinders = models.PositiveIntegerField(default = 0)
    valves_per_cylinder = models.PositiveIntegerField(default = 0)
    transmission_type = models.CharField(max_length=64,default="Automatic")
    gear_box = models.CharField(max_length=64,default="5 gears")
    fuel_type = models.CharField(max_length=64,default="P/D/C")
    mileage = models.FloatField(default = 0)
    tank_capacity = models.FloatField(default = 0)
    emission_norm = models.CharField(max_length=64,default="BS IV")
    length = models.PositiveIntegerField(default = 0)
    width = models.PositiveIntegerField(default = 0)
    weight = models.PositiveIntegerField(default = 0)
    height = models.PositiveIntegerField(default = 0)
    boot_space = models.PositiveIntegerField(default = 0)
    seating = models.PositiveIntegerField(default = 0)
    others = models.TextField(default = "Others")

    def __str__(self):
        return self.car_name

class Tata(models.Model):
    car_name = models.CharField(max_length=20)
    car_pic = models.ImageField(upload_to='tata_cars')
    price = models.CharField(max_length=20)
    about = models.TextField(default = "About")
    engine_type = models.CharField(max_length=64,default="Type 0")
    max_power = models.CharField(max_length=64,default="0 @ 0rpm")
    max_torque = models.CharField(max_length=64,default="0 @ 0rpm")
    no_cylinders = models.PositiveIntegerField(default = 0)
    valves_per_cylinder = models.PositiveIntegerField(default = 0)
    transmission_type = models.CharField(max_length=64,default="Automatic")
    gear_box = models.CharField(max_length=64,default="5 gears")
    fuel_type = models.CharField(max_length=64,default="P/D/C")
    mileage = models.FloatField(default = 0)
    tank_capacity = models.FloatField(default = 0)
    emission_norm = models.CharField(max_length=64,default="BS IV")
    length = models.PositiveIntegerField(default = 0)
    width = models.PositiveIntegerField(default = 0)
    weight = models.PositiveIntegerField(default = 0)
    height = models.PositiveIntegerField(default = 0)
    boot_space = models.PositiveIntegerField(default = 0)
    seating = models.PositiveIntegerField(default = 0)
    others = models.TextField(default = "Others")

    def __str__(self):
        return self.car_name

class Toyota(models.Model):
    car_name = models.CharField(max_length=20)
    car_pic = models.ImageField(upload_to='toyota_cars')
    price = models.CharField(max_length=20)
    about = models.TextField(default = "About")
    engine_type = models.CharField(max_length=64,default="Type 0")
    max_power = models.CharField(max_length=64,default="0 @ 0rpm")
    max_torque = models.CharField(max_length=64,default="0 @ 0rpm")
    no_cylinders = models.PositiveIntegerField(default = 0)
    valves_per_cylinder = models.PositiveIntegerField(default = 0)
    transmission_type = models.CharField(max_length=64,default="Automatic")
    gear_box = models.CharField(max_length=64,default="5 gears")
    fuel_type = models.CharField(max_length=64,default="P/D/C")
    mileage = models.FloatField(default = 0)
    tank_capacity = models.FloatField(default = 0)
    emission_norm = models.CharField(max_length=64,default="BS IV")
    length = models.PositiveIntegerField(default = 0)
    width = models.PositiveIntegerField(default = 0)
    weight = models.PositiveIntegerField(default = 0)
    height = models.PositiveIntegerField(default = 0)
    boot_space = models.PositiveIntegerField(default = 0)
    seating = models.PositiveIntegerField(default = 0)
    others = models.TextField(default = "Others")

    def __str__(self):
        return self.car_name

class Mahindra(models.Model):
    car_name = models.CharField(max_length=20)
    car_pic = models.ImageField(upload_to='mahindra_cars')
    price = models.CharField(max_length=20)
    about = models.TextField(default = "About")
    engine_type = models.CharField(max_length=64,default="Type 0")
    max_power = models.CharField(max_length=64,default="0 @ 0rpm")
    max_torque = models.CharField(max_length=64,default="0 @ 0rpm")
    no_cylinders = models.PositiveIntegerField(default = 0)
    valves_per_cylinder = models.PositiveIntegerField(default = 0)
    transmission_type = models.CharField(max_length=64,default="Automatic")
    gear_box = models.CharField(max_length=64,default="5 gears")
    fuel_type = models.CharField(max_length=64,default="P/D/C")
    mileage = models.FloatField(default = 0)
    tank_capacity = models.FloatField(default = 0)
    emission_norm = models.CharField(max_length=64,default="BS IV")
    length = models.PositiveIntegerField(default = 0)
    width = models.PositiveIntegerField(default = 0)
    weight = models.PositiveIntegerField(default = 0)
    height = models.PositiveIntegerField(default = 0)
    boot_space = models.PositiveIntegerField(default = 0)
    seating = models.PositiveIntegerField(default = 0)
    others = models.TextField(default = "Others")

    def __str__(self):
        return self.car_name

class Honda(models.Model):
    car_name = models.CharField(max_length=20)
    car_pic = models.ImageField(upload_to='honda_cars')
    price = models.CharField(max_length=20)
    about = models.TextField(default = "About")
    engine_type = models.CharField(max_length=64,default="Type 0")
    max_power = models.CharField(max_length=64,default="0 @ 0rpm")
    max_torque = models.CharField(max_length=64,default="0 @ 0rpm")
    no_cylinders = models.PositiveIntegerField(default = 0)
    valves_per_cylinder = models.PositiveIntegerField(default = 0)
    transmission_type = models.CharField(max_length=64,default="Automatic")
    gear_box = models.CharField(max_length=64,default="5 gears")
    fuel_type = models.CharField(max_length=64,default="P/D/C")
    mileage = models.FloatField(default = 0)
    tank_capacity = models.FloatField(default = 0)
    emission_norm = models.CharField(max_length=64,default="BS IV")
    length = models.PositiveIntegerField(default = 0)
    width = models.PositiveIntegerField(default = 0)
    weight = models.PositiveIntegerField(default = 0)
    height = models.PositiveIntegerField(default = 0)
    boot_space = models.PositiveIntegerField(default = 0)
    seating = models.PositiveIntegerField(default = 0)
    others = models.TextField(default = "Others")

    def __str__(self):
        return self.car_name

class Kia(models.Model):
    car_name = models.CharField(max_length=20)
    car_pic = models.ImageField(upload_to='kia_cars')
    price = models.CharField(max_length=20)
    about = models.TextField(default = "About")
    engine_type = models.CharField(max_length=64,default="Type 0")
    max_power = models.CharField(max_length=64,default="0 @ 0rpm")
    max_torque = models.CharField(max_length=64,default="0 @ 0rpm")
    no_cylinders = models.PositiveIntegerField(default = 0)
    valves_per_cylinder = models.PositiveIntegerField(default = 0)
    transmission_type = models.CharField(max_length=64,default="Automatic")
    gear_box = models.CharField(max_length=64,default="5 gears")
    fuel_type = models.CharField(max_length=64,default="P/D/C")
    mileage = models.FloatField(default = 0)
    tank_capacity = models.FloatField(default = 0)
    emission_norm = models.CharField(max_length=64,default="BS IV")
    length = models.PositiveIntegerField(default = 0)
    width = models.PositiveIntegerField(default = 0)
    weight = models.PositiveIntegerField(default = 0)
    height = models.PositiveIntegerField(default = 0)
    boot_space = models.PositiveIntegerField(default = 0)
    seating = models.PositiveIntegerField(default = 0)
    others = models.TextField(default = "Others")

    def __str__(self):
        return self.car_name

etproject/wagonauto/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from . import models

# Create your views here.
def index(request):
    return render(request,'wagonauto/index.html')

class CompanyListView(ListView):
    context_object_name = 'company'
    model = models.Companies

class SuzukiListView(ListView):
    context_object_name = 'suzuki'
    model = models.Suzuki

class HyundaiListView(ListView):
    context_object_name = 'hyundai'
    model = models.Hyundai

class TataListView(ListView):
    context_object_name = 'tata'
    model = models.Tata

class ToyotaListView(ListView):
    context_object_name = 'toyota'
    model = models.Toyota

class MahindraListView(ListView):
    context_object_name = 'mahindra'
    model = models.Mahindra

class HondaListView(ListView):
    context_object_name = 'honda'
    model = models.Honda

class KiaListView(ListView):
    context_object_name = 'kia'
    model = models.Kia

class SuzukiDetailView(DetailView):
    context_object_name = 'suzukidet'
    model = models.Suzuki
    template_name = 'wagonauto/suzuki_detail.html'

class HyundaiDetailView(DetailView):
    context_object_name = 'hyundaidet'
    model = models.Hyundai
    template_name = 'wagonauto/hyundai_detail.html'

class TataDetailView(DetailView):
    context_object_name = 'tatadet'
    model = models.Tata
    template_name = 'wagonauto/tata_detail.html'

class ToyotaDetailView(DetailView):
    context_object_name = 'toyotadet'
    model = models.Toyota
    template_name = 'wagonauto/toyota_detail.html'

class MahindraDetailView(DetailView):
    context_object_name = 'mahindradet'
    model = models.Mahindra
    template_name = 'wagonauto/mahindra_detail.html'

class HondaDetailView(DetailView):
    context_object_name = 'hondadet'
    model = models.Honda
    template_name = 'wagonauto/honda_detail.html'

class KiaDetailView(DetailView):
    context_object_name = 'kiadet'
    model = models.Kia
    template_name = 'wagonauto/kia_detail.html'

class ContactPage(TemplateView):
    template_name = 'wagonauto/contacts.html'

etproject/wagonauto/templates/wagonauto/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <title>WAGONAUTO</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.1/dist/jquery.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/wagonauto.css' %}">
  </head>
  <body>

    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <a class="navbar-brand" href="{% url 'index' %}">Home</a>

      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'wagonauto:clist' %}">Companies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'wagonauto:contlist' %}">Contacts</a>
        </li>
      </ul>
    </nav>

    {% block body_block %}
    {% endblock %}

  </body>
</html>

etproject/wagonauto/templates/wagonauto/companies_list.html
{% extends "wagonauto/base.html" %}
{% block body_block %}
  <div class="container">
    <h1>Select a company</h1>
    <div class="jumbotron">
      <table class="table table-borderless">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <tr>
          {% for comp in company|slice:":3" %}
            {% if comp.id == 2 %}
              <td>
                <a href="{% url 'wagonauto:suzukilist' %}">
                  <div class="card compcardclass">
                    <img class="card-img-top compimgclass" src="{{ comp.logo.url }}" alt="Card image">
                    <div class="card-body">
                      <h4 class="card-title">Maruti {{ comp.company_name }}</h4>
                    </div>
                  </div>
                </a>
              </td>
            {% endif %}
            {% if comp.id == 3 %}
              <td>
                <a href="{% url 'wagonauto:hyundailist' %}">
                  <div class="card compcardclass">
                    <img class="card-img-top compimgclass" src="{{ comp.logo.url }}" alt="Card image">
                    <div class="card-body">
                      <h4 class="card-title">{{ comp.company_name }}</h4>
                    </div>
                  </div>
                </a>
              </td>
            {% endif %}
            {% if comp.id == 4 %}
              <td>
                <a href="{% url 'wagonauto:tatalist' %}">
                  <div class="card compcardclass">
                    <img class="card-img-top compimgclass" src="{{ comp.logo.url }}" alt="Card image">
                    <div class="card-body">
                      <h4 class="card-title">{{ comp.company_name }}</h4>
                    </div>
                  </div>
                </a>
              </td>
            {% endif %}
          {% endfor %}
          </tr>
          <tr>
          {% for comp in company|slice:"3:6" %}
            {% if comp.id == 5 %}
              <td>
                <a href="{% url 'wagonauto:toyotalist' %}">
                  <div class="card compcardclass">
                    <img class="card-img-top compimgclass" src="{{ comp.logo.url }}" alt="Card image">
                    <div class="card-body">
                      <h4 class="card-title">{{ comp.company_name }}</h4>
                    </div>
                  </div>
                </a>
              </td>
            {% endif %}
            {% if comp.id == 6 %}
              <td>
                <a href="{% url 'wagonauto:mahindralist' %}">
                  <div class="card compcardclass">
                    <img class="card-img-top compimgclass" src="{{ comp.logo.url }}" alt="Card image">
                    <div class="card-body">
                      <h4 class="card-title">{{ comp.company_name }}</h4>
                    </div>
                  </div>
                </a>
              </td>
            {% endif %}
            {% if comp.id == 7 %}
              <td>
                <a href="{% url 'wagonauto:hondalist' %}">
                  <div class="card compcardclass">
                    <img class="card-img-top compimgclass" src="{{ comp.logo.url }}" alt="Card image">
                    <div class="card-body">
                      <h4 class="card-title">{{ comp.company_name }}</h4>
                    </div>
                  </div>
                </a>
              </td>
            {% endif %}
          {% endfor %}
          </tr>
          <tr>
          {% for comp in company|slice:"6:7" %}
            {% if comp.id == 8 %}
              <td>
                <a href="{% url 'wagonauto:kialist' %}">
                  <div class="card compcardclass">
                    <img class="card-img-top compimgclass" src="{{ comp.logo.url }}" alt="Card image">
                    <div class="card-body">
                      <h4 class="card-title">{{ comp.company_name }}</h4>
                    </div>
                  </div>
                </a>
              </td>
            {% endif %}
          {% endfor %}
          </tr>
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}

etproject/wagonauto/templates/wagonauto/contacts.html
{% extends "wagonauto/base.html" %}
{% block body_block %}
    <div class="container">
      <div class="jumbotron">
        <form id="pincode-form">
          {{ form.as_p }}
          {% csrf_token %}
          <label for="pincode-input">Enter your pincode:</label><br>
          <input type="text" id="pincode-input" name="pincode"><br>
          <button type="btn btn-primary">Submit</button>
        </form>
        <div id="results"></div>

        <!-- Link to the JavaScript file -->
        <script>
          const form = document.getElementById("pincode-form");
          const pincodeInput = document.getElementById("pincode");
          // Get a reference to the input field
          const input = document.getElementById('pincode-input');

          let postOfficeList = document.getElementById("post-office-list");
          let pincode=0

          form.addEventListener('submit', (event) => {
              // Prevent the form from being submitted
              event.preventDefault();

              // Get the value of the input field
              const pincode = input.value;

              // Store the pincode in local storage
              localStorage.setItem('pincode', pincode);

              // Call the searchAndDisplayCarShowrooms function
              searchAndDisplayCarShowrooms();
            });

            async function searchAndDisplayCarShowrooms() {
              // Get the pincode from local storage
              const pincode = localStorage.getItem('pincode');

              // Replace YOUR_API_KEY with your actual API key
              const API_KEY = 'AIzaSyAXmXks_i_gWF21TnqStIjtPGQ0Isa8wHs';

              // Replace YOUR_SEARCH_ENGINE_ID with the ID of your search engine
              const SEARCH_ENGINE_ID = '5647795047ae2441e';

              // Make a GET request to the Google Search API, passing in the pincode, search engine ID, and API key as query parameters
              const response = await fetch(`https://www.googleapis.com/customsearch/v1?q=${pincode}+car+showrooms+motors&cx=${SEARCH_ENGINE_ID}&key=${API_KEY}`);
              console.log(response)

              // Parse the response as JSON
              const data = await response.json();

              // Get a reference to the element where the search results will be displayed
              const resultsDiv = document.getElementById('results');

              // Clear the current contents of the results div
              resultsDiv.innerHTML = '';

              // Iterate through the search results and create a list item for each one
              for (const item of data.items) {
                const li = document.createElement('li');
                li.innerHTML = `<a href="${item.link}">${item.title}</a>`;
                resultsDiv.appendChild(li);
              }
            }

        </script>
      </div>
    </div>
{% endblock %}

etproject/wagonauto/templates/wagonauto/honda_detail.html
{% extends "wagonauto/base.html" %}
{% block body_block %}
<div class="container">
  <img src="{{ hondadet.car_pic.url }}" alt="Card image" class="rounded mx-auto d-block">
</div>
<div class="container">
  <h1>Honda {{ hondadet.car_name }}</h1>
  <p>Ex-showroom price: {{ hondadet.price }}</p>
  <br>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <h5><a class="nav-link active" data-toggle="tab" href="#home">About</a></h5>
    </li>
    <li class="nav-item">
      <h5><a class="nav-link" data-toggle="tab" href="#menu1">Engine & transmossion</a></h5>
    </li>
    <li class="nav-item">
      <h5><a class="nav-link" data-toggle="tab" href="#menu2">Fuel & Performance</a></h5>
    </li>
    <li class="nav-item">
      <h5><a class="nav-link" data-toggle="tab" href="#menu3">Dimentions & Capacity</a></h5>
    </li>
    <li class="nav-item">
      <h5><a class="nav-link" data-toggle="tab" href="#menu4">Other Comforts</a></h5>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div id="home" class="container tab-pane active"><br>
      <h4>Maruti Suzuki {{ hondadet.car_name }}</h4>
      <p>{{ hondadet.about }}</p>
    </div>
    <div id="menu1" class="container tab-pane fade"><br>
      <h4>Engine Type</h4>
      <p>{{ hondadet.transmission_type }}</p>
      <h4>Max power</h4>
      <p>{{ hondadet.max_power }}</p>
      <h4>Max Torque</h4>
      <p>{{ hondadet.max_torque }}</p>
      <h4>Number of Cylinders</h4>
      <p>{{ hondadet.no_cylinders }}</p>
      <h4>Valves per Cylinder</h4>
      <p>{{ hondadet.valves_per_cylinder }}</p>
      <h4>Transmission Type</h4>
      <p>{{ hondadet.transmission_type }}</p>
      <h4>Gear Box</h4>
      <p>{{ hondadet.gear_box }}</p>
    </div>
    <div id="menu2" class="container tab-pane fade"><br>
      <h4>Fuel Type</h4>
      <p>{{ hondadet.fuel_type }}</p>
      <h4>Mileage</h4>
      <p>{{ hondadet.mileage }}</p>
      <h4>Fuel Tank Capacity</h4>
      <p>{{ hondadet.tank_capacity }}</p>
      <h4>Emission Norm Compliance</h4>
      <p>{{ hondadet.emission_norm }}</p>
    </div>
    <div id="menu3" class="container tab-pane fade"><br>
      <h4>Length (mm)</h4>
      <p>{{ hondadet.length }}</p>
      <h4>Width (mm)</h4>
      <p>{{ hondadet.width }}</p>
      <h4>Height (mm)</h4>
      <p>{{ hondadet.height }}</p>
      <h4>Gross Weight (Kg)</h4>
      <p>{{ hondadet.weight }}</p>
      <h4>Boot Space</h4>
      <p>{{ hondadet.boot_space }}</p>
      <h4>Number of seats</h4>
      <p>{{ hondadet.seating }}</p>
    </div>
    <div id="menu4" class="container tab-pane fade"><br>
      <h4>Special features</h4>
      <p>{{ hondadet.others }}</p>
    </div>
  </div>
</div>
{% endblock %}

etproject/wagonauto/templates/wagonauto/hyundai_detail.html
{% extends "wagonauto/base.html" %}
{% block body_block %}
<div class="container">
  <img src="{{ hyundaidet.car_pic.url }}" alt="Card image" class="rounded mx-auto d-block">
</div>
<div class="container">
  <h1>Hyundai {{ hyundaidet.car_name }}</h1>
  <p>Ex-showroom price: {{ hyundaidet.price }}</p>
  <br>
  <!-- Nav tabs -->
  <ul class="nav nav-tabs" role="tablist">
    <li class="nav-item">
      <h5><a class="nav-link active" data-toggle="tab" href="#home">About</a></h5>
    </li>
    <li class="nav-item">
      <h5><a class="nav-link" data-toggle="tab" href="#menu1">Engine & transmossion</a></h5>
    </li>
    <li class="nav-item">
      <h5><a class="nav-link" data-toggle="tab" href="#menu2">Fuel & Performance</a></h5>
    </li>
    <li class="nav-item">
      <h5><a class="nav-link" data-toggle="tab" href="#menu3">Dimentions & Capacity</a></h5>
    </li>
    <li class="nav-item">
      <h5><a class="nav-link" data-toggle="tab" href="#menu4">Other Comforts</a></h5>
    </li>
  </ul>

  <!-- Tab panes -->
  <div class="tab-content">
    <div id="home" class="container tab-pane active"><br>
      <h4>Maruti Suzuki {{ hyundaidet.car_name }}</h4>
      <p>{{ hyundaidet.about }}</p>
    </div>
    <div id="menu1" class="container tab-pane fade"><br>
      <h4>Engine Type</h4>
      <p>{{ hyundaidet.transmission_type }}</p>
      <h4>Max power</h4>
      <p>{{ hyundaidet.max_power }}</p>
      <h4>Max Torque</h4>
      <p>{{ hyundaidet.max_torque }}</p>
      <h4>Number of Cylinders</h4>
      <p>{{ hyundaidet.no_cylinders }}</p>
      <h4>Valves per Cylinder</h4>
      <p>{{ hyundaidet.valves_per_cylinder }}</p>
      <h4>Transmission Type</h4>
      <p>{{ hyundaidet.transmission_type }}</p>
      <h4>Gear Box</h4>
      <p>{{ hyundaidet.gear_box }}</p>
    </div>
    <div id="menu2" class="container tab-pane fade"><br>
      <h4>Fuel Type</h4>
      <p>{{ hyundaidet.fuel_type }}</p>
      <h4>Mileage</h4>
      <p>{{ hyundaidet.mileage }}</p>
      <h4>Fuel Tank Capacity</h4>
      <p>{{ hyundaidet.tank_capacity }}</p>
      <h4>Emission Norm Compliance</h4>
      <p>{{ hyundaidet.emission_norm }}</p>
    </div>
    <div id="menu3" class="container tab-pane fade"><br>
      <h4>Length (mm)</h4>
      <p>{{ hyundaidet.length }}</p>
      <h4>Width (mm)</h4>
      <p>{{ hyundaidet.width }}</p>
      <h4>Height (mm)</h4>
      <p>{{ hyundaidet.height }}</p>
      <h4>Gross Weight (Kg)</h4>
      <p>{{ hyundaidet.weight }}</p>
      <h4>Boot Space</h4>
      <p>{{ hyundaidet.boot_space }}</p>
      <h4>Number of seats</h4>
      <p>{{ hyundaidet.seating }}</p>
    </div>
    <div id="menu4" class="container tab-pane fade"><br>
      <h4>Special features</h4>
      <p>{{ hyundaidet.others }}</p>
    </div>
  </div>
</div>
{% endblock %}